apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: eks-project
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: 195275633219.dkr.ecr.us-east-1.amazonaws.com/eks-repo:nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"